[package]
name = "testgame"
version = "0.1.0"
authors = ["Mikael Myyr√§ <mikael.myyrae@gmail.com>"]
edition = "2018"

[dependencies]
glium = "0.24.0"
nalgebra = "0.18.0"

[dependencies.moleengine]
path = "../../engine"
features = ["all"]

[dependencies.microprofile]
version = "0.1.0"
